"""Update theme category table

Revision ID: c9d91f61d773
Revises: d276dabcfb37
Create Date: 2024-06-11 16:37:43.825954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d91f61d773"
down_revision: Union[str, None] = "d276dabcfb37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ua_local", sa.String(length=20), nullable=False),
        sa.Column("ru_local", sa.String(length=20), nullable=False),
        sa.Column("en_local", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("theme_categories")
    # ### end Alembic commands ###
