import os
import zipfile

# from utils.theme_preview import CreateComputerPreview
from .color_name import ColorName
from .color_brightness import ColorBrightness


# class CreateComputerTheme(ColorName,
#                           ColorBrightness,
#                           CreateComputerPreview):
class CreateComputerTheme(ColorName,
                          ColorBrightness):
    
    async def _create_zip_archive(self, image_file, text_file, output_filename):
        with zipfile.ZipFile(output_filename, 'w') as zipf:
            zipf.write(image_file, f'background.{image_file.split(".")[-1]}')
            zipf.write(text_file, f'colors.{text_file.split(".")[-1]}')
    
    
    async def create_pc_theme(self, data, bot_name):
        chat_id = data.get('chat_id')
        image_path = data.get('wallpaper_path')
        background_color = data.get('bg_color')
        primary_text_color = data.get('primary_color')
        secondary_text_color = data.get('secondary_color')
        alfa = data.get('alfa_chanel')
        
        color_name: str = await self.hex_to_color_name(background_color)
        color_name = color_name.capitalize()

        background_color2 = await self._adjust_color_brightness(background_color)
        background_alfa = alfa
        file_name = 'colors.tdesktop-theme'
        zip_name = os.path.join('src',
                                'users_data',
                                str(chat_id),
                                f'{color_name}_theme_by-{bot_name}.tdesktop-theme')

        write_data = [
            "windowShadowFg: #000000bf;",
            "windowShadowFgFallback: #181818;",
            "shadowFg: #25252540;",
            "slideFadeOutBg: #0000003c;",
            "slideFadeOutShadowFg: windowShadowFg;",
            "imageBg: #181818;",
            "outlineButtonBg: windowBg;",
            "outlineButtonBgOver: lightButtonBgOver;",
            "outlineButtonBgRipple: lightButtonBgRipple;",
            f"menuBg: {background_color2};",
            "menuBgRipple: windowBgRipple;",
            "menuSubmenuArrowFg: windowFg;",
            "menuFgDisabled: #cccccc;",
            "scrollBarBg: #a7a7a753;",
            "scrollBg: #a7a7a71a;",
            "smallCloseIconFg: #a7a7a7;",
            "radialBg: #00000056;",
            "botKbDownBg: menuBgRipple;",
            "tooltipBg: #eef2f5;",
            "tooltipFg: windowFg;",
            "tooltipBorderFg: #c9d1db;",
            "titleShadow: #25252540;",
            "titleButtonCloseBg: titleButtonBg;",
            "titleButtonCloseFg: titleButtonFg;",
            "titleFg: #a7a7a7;",
            "layerBg: #00000090;",
            "cancelIconFg: menuIconFg;",
            "cancelIconFgOver: menuIconFgOver;",
            "boxBg: windowBg;",
            "boxTextFg: windowFg;",
            "boxTextFgGood: #4ab44a;",
            "boxTextFgError: #d84d4d;",
            "boxTitleAdditionalFg: windowBg;",
            "boxTitleCloseFg: cancelIconFg;",
            "boxTitleCloseFgOver: cancelIconFgOver;",
            "contactsBg: windowBg;",
            "contactsNameFg: boxTextFg;",
            "contactsStatusFg: windowSubTextFg;",
            "photoCropFadeBg: layerBg;",
            "callArrowFg: #2ab32a;",
            "callArrowMissedFg: #dd5b4a;",
            "introBg: windowBg;",
            "introTitleFg: windowBoldFg;",
            "introDescriptionFg: windowSubTextFg;",
            "introErrorFg: windowSubTextFg;",
            "introCoverTopBg: windowBg;",
            "introCoverBottomBg: windowBg;",
            "introCoverPlaneInner: #999999;",
            "introCoverPlaneOuter: #888888;",
            "dialogsMenuIconFg: menuIconFg;",
            "dialogsMenuIconFgOver: menuIconFgOver;",
            "dialogsBg: windowBg;",
            "dialogsNameFg: windowBoldFg;",
            "dialogsChatIconFg: dialogsNameFg;",
            "dialogsDateFg: windowSubTextFg;",
            "dialogsDraftFg: #dd4b39;",
            "dialogsVerifiedIconBg: #40a7e3;",
            "dialogsNameFgOver: windowBoldFgOver;",
            "dialogsChatIconFgOver: dialogsNameFgOver;",
            "dialogsTextFgServiceOver: dialogsTextFgService;",
            "dialogsDraftFgOver: dialogsDraftFg;",
            "dialogsVerifiedIconBgOver: dialogsVerifiedIconBg;",
            "dialogsVerifiedIconFgOver: dialogsVerifiedIconFg;",
            "dialogsSendingIconFgOver: dialogsSendingIconFg;",
            f"dialogsSentIconFgOver: {background_color};",
            "dialogsUnreadBgOver: dialogsUnreadBg;",
            "dialogsUnreadFgOver: dialogsUnreadFg;",
            "dialogsRippleBg: windowBgRipple;",
            "topBarBg: windowBg;",
            "emojiPanCategories: emojiPanBg;",
            "emojiPanHeaderBg: emojiPanBg;",
            "emojiIconFg: #a7a7a7;",
            "stickerPreviewBg: #00000090;",
            "historyTextInFg: windowFg;",
            "historyTextOutFg: windowFg;",
            "historyFileNameInFg: historyTextInFg;",
            "historyFileNameOutFg: historyTextOutFg;",
            "historyCallArrowInFg: callArrowFg;",
            "historyCallArrowInFgSelected: callArrowFg;",
            "historyCallArrowMissedInFg: callArrowMissedFg;",
            "historyCallArrowMissedInFgSelected: callArrowMissedFg;",
            "historyCallArrowOutFg: historyCallArrowInFg;",
            "historyCallArrowOutFgSelected: historyCallArrowInFgSelected;",
            "historyUnreadBarBorder: shadowFg;",
            "historyForwardChooseBg: #00000099;",
            "historyPeer1NameFgSelected: historyPeer1NameFg;",
            f"historyPeer1UserpicBg: {background_color};",
            f"historyPeer1UserpicBg2: {secondary_text_color};",
            "historyPeer2NameFgSelected: historyPeer2NameFg;",
            f"historyPeer2UserpicBg: {background_color};",
            f"historyPeer2UserpicBg2: {secondary_text_color};",
            "historyPeer3NameFgSelected: historyPeer3NameFg;",
            f"historyPeer3UserpicBg: {background_color};",
            f"historyPeer3UserpicBg2: {secondary_text_color};",
            "historyPeer4NameFgSelected: historyPeer4NameFg;",
            f"historyPeer4UserpicBg: {background_color};",
            f"historyPeer4UserpicBg2: {secondary_text_color};",
            "historyPeer5NameFgSelected: historyPeer5NameFg;",
            f"historyPeer5UserpicBg: {background_color};",
            f"historyPeer5UserpicBg2: {secondary_text_color};",
            "historyPeer6NameFgSelected: historyPeer6NameFg;",
            f"historyPeer6UserpicBg: {background_color};",
            f"historyPeer6UserpicBg2: {secondary_text_color};",
            "historyPeer7NameFgSelected: historyPeer7NameFg;",
            f"historyPeer7UserpicBg: {background_color};",
            f"historyPeer7UserpicBg2: {secondary_text_color};",
            "historyPeer8NameFgSelected: historyPeer8NameFg;",
            f"historyPeer8UserpicBg: {background_color};",
            f"historyPeer8UserpicBg2: {secondary_text_color};",
            "historyPeerArchiveUserpicBg: #252525;",
            "historyScrollBarBg: #b4b4b453;",
            "historyScrollBg: #9999991a;",
            "msgSelectOverlay: #00000080;",
            "msgStickerOverlay: #00000080;",
            "msgServiceBgSelected: #565656a2;",
            "msgImgReplyBarColor: msgServiceFg;",
            "msgOutMonoFg: msgInMonoFg;",
            f"msgDateImgBg: {background_color2};",
            "msgDateImgBgOver: #00000095;",
            "msgFileThumbLinkInFgSelected: lightButtonFgOver;",
            "msgFileThumbLinkOutFgSelected: lightButtonFgOver;",
            "msgFileInBgOver: #959595;",
            "msgFileOutBgOver: #959595;",
            "msgFileOutBgSelected: #999999;",
            "msgFile1Bg: #72b1df;",
            "msgFile1BgDark: #5c9ece;",
            "msgFile1BgOver: #5294c4;",
            "msgFile1BgSelected: #5099d0;",
            "msgFile2Bg: #61b96e;",
            "msgFile2BgDark: #4da859;",
            "msgFile2BgOver: #44a050;",
            "msgFile2BgSelected: #46a07e;",
            "msgFile3Bg: #e47272;",
            "msgFile3BgDark: #cd5b5e;",
            "msgFile3BgOver: #c35154;",
            "msgFile3BgSelected: #9f6a82;",
            "msgFile4Bg: #efc274;",
            "msgFile4BgDark: #e6a561;",
            "msgFile4BgOver: #dc9c5a;",
            "msgFile4BgSelected: #b19d84;",
            "historyFileInRadialFg: historyFileInIconFg;",
            "historyFileInRadialFgSelected: historyFileInIconFgSelected;",
            "historyFileOutIconFg: #505050;",
            "historyFileOutRadialFg: historyFileOutIconFg;",
            "historyFileOutRadialFgSelected: historyFileOutIconFgSelected;",
            "historyFileThumbRadialFg: historyFileThumbIconFg;",
            "historyFileThumbRadialFgSelected: historyFileThumbIconFgSelected;",
            "historyVideoMessageProgressFg: historyFileThumbIconFg;",
            "msgWaveformInInactive: #696969;",
            "msgBotKbOverBgAdd: #49494995;",
            "msgBotKbRippleBg: #56565695;",
            "mediaOutFg: #a7a7a7;",
            "mediaOutFgSelected: msgOutDateFgSelected;",
            "youtubePlayIconBg: #e83131c8;",
            "videoPlayIconBg: #000000c8;",
            "toastBg: #000000b2;",
            "reportSpamBg: #3a3a3a;",
            "reportSpamFg: windowFg;",
            "historyToDownBg: #252525;",
            "historyToDownBgOver: #494949;",
            "historyToDownBgRipple: #565656;",
            "historyToDownFg: #a7a7a7;",
            "historyToDownShadow: #00000040;",
            f"historyComposeAreaBg: {background_color};",
            "historyComposeAreaFgService: msgInDateFg;",
            f"historyReplyBg: {background_color};",
            "historyReplyCancelFg: cancelIconFg;",
            "historyReplyCancelFgOver: cancelIconFgOver;",
            "historyComposeButtonBg: historyComposeAreaBg;",
            "historyComposeButtonBgRipple: windowBgRipple;",
            "mapPointDrop: #fd4444;",
            "overviewCheckBg: #00000040;",
            "overviewCheckBorder: #a7a7a7;",
            "overviewCheckFg: windowBg;",
            "overviewPhotoSelectOverlay: #00000040;",
            "profileVerifiedCheckBg: #40a7e3;",
            "profileAdminStartFg: #40a7e3;",
            "profileAdminStarFgOver: profileAdminStartFg;",
            "profileOtherAdminStarFg: windowSubTextFg;",
            "profileOtherAdminStarFgOver: windowSubTextFg;",
            "notificationsBoxMonitorFg: windowFg;",
            "notificationSampleUserpicFg: #252525;",
            "notificationSampleCloseFg: #252525;",
            "notificationSampleTextFg: #a7a7a7;",
            "changePhoneSimcardFrom: notificationSampleTextFg;",
            "changePhoneSimcardTo: notificationSampleNameFg;",
            "mainMenuBg: windowBg;",
            "mainMenuCoverBg: windowBg;",
            "mainMenuCloudBg: #656565;",
            "mediaPlayerDisabledFg: #7baaf7;",
            "mediaviewFileBg: windowBg;",
            "mediaviewFileNameFg: windowFg;",
            "mediaviewFileSizeFg: windowSubTextFg;",
            "mediaviewFileRedCornerFg: #d55959;",
            "mediaviewFileYellowCornerFg: #e8a659;",
            "mediaviewFileGreenCornerFg: #49a957;",
            "mediaviewFileBlueCornerFg: #599dcf;",
            "mediaviewMenuBg: windowBg;",
            "mediaviewMenuBgOver: #494949;",
            "mediaviewMenuBgRipple: #565656;",
            "mediaviewBg: #00000099;",
            "mediaviewVideoBg: imageBg;",
            "mediaviewControlBg: #0000003c;",
            "mediaviewCaptionBg: #11111180;",
            "mediaviewCaptionFg: mediaviewControlFg;",
            "mediaviewTextLinkFg: #7baaf7;",
            "mediaviewSaveMsgFg: toastFg;",
            "mediaviewTransparentFg: #cccccc;",
            "callBg: #3a3a3af2;",
            "callFingerprintBg: #00000066;",
            "callStatusFg: #a7a7a7;",
            "callAnswerBg: #64c15b;",
            "callAnswerRipple: #52b149;",
            "callAnswerBgOuter: #50eb4126;",
            "callHangupBg: #d75a5a;",
            "callHangupRipple: #c04646;",
            "callCancelFg: #999999;",
            "callCancelRipple: #f1f1f1;",
            "callBarBg: #3a3a3a;",
            "callBarMuteRipple: #565656;",
            "callBarBgMuted: #565656;",
            "callBarUnmuteRipple: #494949;",
            "importantTooltipBg: toastBg;",
            "importantTooltipFg: toastFg;",
            "importantTooltipFgLink: mediaviewTextLinkFg;",
            f"sideBarBg: {background_color2};",
            f"sideBarBadgeBgMuted: {background_color};",
            f"msgInBg : {background_color2}{background_alfa};",
            f"msgOutBg : {background_color}{background_alfa};",
            f"windowBg : {background_color};",
            f"boxDividerBg : {background_color};",
            f"windowFgActive : {background_color};",
            f"imageBgTransparent : {background_color};",
            f"attentionButtonBgRipple : {background_color};",
            f"outlineButtonOutlineFg : {background_color};",
            f"menuBgOver : {background_color};",
            f"menuSeparatorFg : {background_color};",
            f"smallCloseIconFgOver : {background_color};",
            f"radialFg : {background_color};",
            f"inputBorderFg : {background_color};",
            f"filterInputActiveBg : {background_color};",
            f"filterInputInactiveBg : {background_color};",
            f"botKbColor : {background_color};",
            f"titleBg : {background_color};",
            f"titleBgActive : {background_color};",
            f"titleButtonBg : {background_color};",
            f"titleButtonBgOver : {background_color};",
            f"titleButtonBgActive : {background_color};",
            f"titleButtonBgActiveOver : {background_color};",
            f"titleButtonCloseBgOver : {background_color};",
            f"titleButtonCloseBgActive : {background_color};",
            f"titleButtonCloseBgActiveOver : {background_color};",
            f"trayCounterBg : {background_color};",
            f"trayCounterBgMacInvert : {background_color};",
            f"boxSearchBg : {background_color};",
            f"membersAboutLimitFg : {background_color};",
            f"introCoverIconsFg : {background_color};",
            f"introCoverPlaneTrace : {background_color};",
            f"introCoverPlaneTop : {background_color};",
            f"dialogsUnreadFg : {background_color};",
            f"dialogsNameFgActive : {background_color};",
            f"dialogsChatIconFgActive : {background_color};",
            f"dialogsDateFgActive : {background_color};",
            f"dialogsTextFgActive : {background_color};",
            f"dialogsTextFgServiceActive : {background_color};",
            f"dialogsVerifiedIconFgActive : {background_color};",
            f"dialogsSendingIconFgActive : {background_color};",
            f"dialogsSentIconFgActive : {background_color};",
            f"dialogsUnreadFgActive : {background_color};",
            f"searchedBarBg : {background_color};",
            f"emojiPanBg : {background_color};",
            f"historyTextInFgSelected : {background_color};",
            f"historyTextOutFgSelected : {background_color};",
            f"historyLinkInFgSelected : {background_color};",
            f"historyLinkOutFgSelected : {background_color};",
            f"historyFileNameInFgSelected : {background_color};",
            f"historyFileNameOutFgSelected : {background_color};",
            f"historyUnreadBarBg : {background_color};",
            f"msgInServiceFgSelected : {background_color};",
            f"msgOutServiceFgSelected : {background_color};",
            f"msgInDateFgSelected : {background_color};",
            f"msgOutDateFgSelected : {background_color};",
            f"msgServiceBg : {background_color};",
            f"msgInReplyBarSelColor : {background_color};",
            f"msgOutReplyBarSelColor : {background_color};",
            f"msgInMonoFgSelected : {background_color};",
            f"msgOutMonoFgSelected : {background_color};",
            f"msgDateImgFg : {primary_text_color};",
            f"msgFileThumbLinkOutFg : {primary_text_color};",
            f"msgFileOutBg : {primary_text_color};",
            f"historyFileInIconFg : {background_color};",
            f"historyFileInIconFgSelected : {background_color};",
            f"historyFileOutIconFgSelected : {background_color};",
            f"historyFileThumbIconFg : {background_color};",
            f"historyPinnedBg : {background_color};",
            f"historyComposeButtonBgOver : {background_color};",
            f"overviewCheckFgActive : {background_color};",
            f"mediaPlayerBg : {background_color};",
            f"mediaviewSaveMsgBg : {background_color};",
            f"notificationBg : {background_color};",
            f"sideBarBgActive : {background_color};",
            f"sideBarBadgeFg : {primary_text_color};",
            f"windowFg : {primary_text_color};",
            f"windowFgOver : {primary_text_color};",
            f"windowSubTextFg : {primary_text_color};",
            f"windowSubTextFgOver : {primary_text_color};",
            f"windowBoldFg : {primary_text_color};",
            f"windowBoldFgOver : {primary_text_color};",
            f"windowBgActive : {primary_text_color};",
            f"windowActiveTextFg : {primary_text_color};",
            f"activeButtonBgRipple : {primary_text_color};",
            f"activeButtonFg : {primary_text_color};",
            f"activeButtonFgOver : {primary_text_color};",
            f"activeButtonSecondaryFg : {primary_text_color};",
            f"activeButtonSecondaryFgOver : {primary_text_color};",
            f"activeLineFg : {primary_text_color};",
            f"activeLineFgError : {primary_text_color};",
            f"lightButtonFg : {primary_text_color};",
            f"lightButtonFgOver : {primary_text_color};",
            f"attentionButtonFg : {primary_text_color};",
            f"attentionButtonFgOver : {primary_text_color};",
            f"menuIconFgOver : {primary_text_color};",
            f"filterInputBorderFg : {primary_text_color};",
            f"sliderBgInactive : {primary_text_color};",
            f"sliderBgActive : {primary_text_color};",
            f"titleButtonFg : {primary_text_color};",
            f"titleButtonFgOver : {primary_text_color};",
            f"titleButtonFgActive : {primary_text_color};",
            f"titleButtonFgActiveOver : {primary_text_color};",
            f"titleButtonCloseFgOver : {primary_text_color};",
            f"titleButtonCloseFgActive : {primary_text_color};",
            f"titleButtonCloseFgActiveOver : {primary_text_color};",
            f"titleFgActive : {primary_text_color};",
            f"trayCounterFg : {primary_text_color};",
            f"trayCounterFgMacInvert : {primary_text_color};",
            f"boxTitleFg : {primary_text_color};",
            f"contactsStatusFgOver : {primary_text_color};",
            f"contactsStatusFgOnline : {primary_text_color};",
            f"photoCropPointFg : {primary_text_color};",
            f"dialogsTextFg : {primary_text_color};",
            f"dialogsTextFgService : {primary_text_color};",
            f"dialogsVerifiedIconFg : {primary_text_color};",
            f"dialogsSendingIconFg : {primary_text_color};",
            f"dialogsSentIconFg : {primary_text_color};",
            f"dialogsUnreadBg : {primary_text_color};",
            f"dialogsArchiveFg : {primary_text_color};",
            f"dialogsDateFgOver : {primary_text_color};",
            f"dialogsTextFgOver : {primary_text_color};",
            f"dialogsUnreadBgMutedOver : {primary_text_color};",
            f"dialogsArchiveFgOver : {primary_text_color};",
            f"dialogsDraftFgActive : {primary_text_color};",
            f"dialogsVerifiedIconBgActive : {primary_text_color};",
            f"dialogsUnreadBgActive : {primary_text_color};",
            f"dialogsUnreadBgMutedActive : {primary_text_color};",
            f"dialogsRippleBgActive : {primary_text_color};",
            f"dialogsForwardBg : {primary_text_color};",
            f"dialogsForwardFg : {primary_text_color};",
            f"searchedBarFg : {primary_text_color};",
            f"emojiPanHeaderFg : {primary_text_color};",
            f"emojiIconFgActive : {primary_text_color};",
            f"stickerPanDeleteBg : {primary_text_color};",
            f"stickerPanDeleteFg : {primary_text_color};",
            f"historyLinkInFg : {primary_text_color};",
            f"historyLinkOutFg : {primary_text_color};",
            f"historyOutIconFg : {primary_text_color};",
            f"historyOutIconFgSelected : {primary_text_color};",
            f"historyIconFgInverted : {primary_text_color};",
            f"historySendingOutIconFg : {primary_text_color};",
            f"historySendingInIconFg : {primary_text_color};",
            f"historySendingInvertedIconFg : {primary_text_color};",
            f"historyUnreadBarFg : {primary_text_color};",
            f"historyForwardChooseFg : {primary_text_color};",
            f"historyPeer1NameFg : {primary_text_color};",
            f"historyPeer2NameFg : {primary_text_color};",
            f"historyPeer3NameFg : {primary_text_color};",
            f"historyPeer4NameFg : {primary_text_color};",
            f"historyPeer5NameFg : {primary_text_color};",
            f"historyPeer6NameFg : {primary_text_color};",
            f"historyPeer7NameFg : {primary_text_color};",
            f"historyPeer8NameFg : {primary_text_color};",
            f"historyPeerUserpicFg : {primary_text_color};",
            f"historyPeerSavedMessagesBg : {background_color};",
            f"historyPeerSavedMessagesBg2 : {background_color2};",
            f"historyScrollBarBgOver : {primary_text_color};",
            f"historyScrollBgOver : {primary_text_color};",
            f"msgInServiceFg : {primary_text_color};",
            f"msgOutServiceFg : {primary_text_color};",
            f"msgServiceFg : {primary_text_color};",
            f"msgFileThumbLinkInFg : {primary_text_color};",
            f"msgFileInBg : {primary_text_color};",
            f"msgFileInBgSelected : {primary_text_color};",
            f"historyFileThumbIconFgSelected : {primary_text_color};",
            f"msgWaveformInActive : {primary_text_color};",
            f"msgWaveformInActiveSelected : {primary_text_color};",
            f"msgWaveformInInactiveSelected : {primary_text_color};",
            f"msgWaveformOutActive : {primary_text_color};",
            f"msgWaveformOutActiveSelected : {primary_text_color};",
            f"msgWaveformOutInactive : {primary_text_color};",
            f"msgWaveformOutInactiveSelected : {primary_text_color};",
            f"msgBotKbIconFg : {primary_text_color};",
            f"mediaInFgSelected : {primary_text_color};",
            f"youtubePlayIconFg : {primary_text_color};",
            f"videoPlayIconFg : {primary_text_color};",
            f"toastFg : {primary_text_color};",
            f"historyToDownFgOver : {primary_text_color};",
            f"historyComposeAreaFg : {primary_text_color};",
            f"historyComposeIconFg : {primary_text_color};",
            f"historyComposeIconFgOver : {primary_text_color};",
            f"historySendIconFg : {primary_text_color};",
            f"historySendIconFgOver : {primary_text_color};",
            f"historyReplyIconFg : {primary_text_color};",
            f"mapPointDot : {primary_text_color};",
            f"overviewCheckBgActive : {primary_text_color};",
            f"profileStatusFgOver : {primary_text_color};",
            f"profileVerifiedCheckFg : {primary_text_color};",
            f"notificationsBoxScreenBg : {primary_text_color};",
            f"notificationSampleNameFg : {primary_text_color};",
            f"mainMenuCoverFg : {primary_text_color};",
            f"mainMenuCloudFg : {primary_text_color};",
            f"mediaPlayerActiveFg : {primary_text_color};",
            f"mediaPlayerInactiveFg : {primary_text_color};",
            f"mediaviewFileExtFg : {primary_text_color};",
            f"mediaviewMenuFg : {primary_text_color};",
            f"mediaviewControlFg : {primary_text_color};",
            f"mediaviewPlaybackActive : {primary_text_color};",
            f"mediaviewPlaybackActiveOver : {primary_text_color};",
            f"mediaviewPlaybackInactiveOver : {primary_text_color};",
            f"mediaviewPlaybackProgressFg : {primary_text_color};",
            f"mediaviewPlaybackIconFgOver : {primary_text_color};",
            f"mediaviewTransparentBg : {primary_text_color};",
            f"callNameFg : {primary_text_color};",
            f"callIconFg : {primary_text_color};",
            f"callCancelBg : {primary_text_color};",
            f"callBarFg : {primary_text_color};",
            f"sideBarBgRipple : {primary_text_color};",
            f"sideBarTextFgActive : {primary_text_color};",
            f"sideBarIconFgActive : {primary_text_color};",
            f"sideBarBadgeBg : {background_color2};",
            f"windowBgOver : {secondary_text_color};",
            f"windowBgRipple : {secondary_text_color};",
            f"activeButtonBg : {secondary_text_color};",
            f"activeButtonBgOver : {secondary_text_color};",
            f"lightButtonBg : {secondary_text_color};",
            f"lightButtonBgOver : {secondary_text_color};",
            f"lightButtonBgRipple : {secondary_text_color};",
            f"attentionButtonBgOver : {secondary_text_color};",
            f"menuIconFg : {secondary_text_color};",
            f"placeholderFg : {secondary_text_color};",
            f"placeholderFgActive : {secondary_text_color};",
            f"checkboxFg : {secondary_text_color};",
            f"botKbBg : {secondary_text_color};",
            f"trayCounterBgMute : {secondary_text_color};",
            f"contactsBgOver : {secondary_text_color};",
            f"dialogsUnreadBgMuted : {secondary_text_color};",
            f"dialogsBgOver : {secondary_text_color};",
            f"dialogsBgActive : {secondary_text_color};",
            f"msgInBgSelected : {secondary_text_color};",
            f"msgOutBgSelected : {secondary_text_color};",
            f"msgInShadow : {background_color};",
            f"msgInShadowSelected : {secondary_text_color};",
            f"msgOutShadow : {background_color2};",
            f"msgOutShadowSelected : {secondary_text_color};",
            f"msgInDateFg : {secondary_text_color};",
            f"msgOutDateFg : {secondary_text_color};",
            f"msgInReplyBarColor : {secondary_text_color};",
            f"msgOutReplyBarColor : {secondary_text_color};",
            f"msgInMonoFg : {secondary_text_color};",
            f"msgDateImgBgSelected : {secondary_text_color};",
            f"mediaInFg : {secondary_text_color};",
            f"mediaviewPlaybackInactive : {secondary_text_color};",
            f"mediaviewPlaybackIconFg : {secondary_text_color};",
            f"sideBarTextFg : {primary_text_color};",
            f"sideBarIconFg : {primary_text_color};",
            f"callMuteRipple: {background_color}12;",
            f"scrollBgOver: {background_color}2c;",
            f"scrollBarBgOver: {background_color}7a;",
        ]

        txt_file_path = os.path.join('src', 'users_data', str(chat_id), file_name)

        with open(txt_file_path, 'w') as file:
            for item in write_data:
                file.write(str(item) + "\n")

        await self._create_zip_archive(image_path, txt_file_path, zip_name)

        # preview_bg = await self._adjust_color_brightness(secondary_text_color, 0.5)
        # preview = await self.create_pc_preview(
        #     bot_name, chat_id, image_path, preview_bg, background_color,
        #     background_color2, secondary_text_color, primary_text_color, background_alfa
        # )
        
        # return zip_name, preview
        return zip_name
